### ISSUE TITLE
404 Error on Detail Page Link with Route Enhancer and External Product Sysfolder

### ISSUE THREAD

**Issue by crookoo** [extcode/cart_products#209]
## Bug Report

**Current Behavior**
The link from the list view to the detail view results in a 404 error as soon as
a) the storage folder in which the products are located is outside the root page tree and
b) an Extbase route enhancer is switched on.

**Expected behavior/output**
The link from the list view to the product detail page should work as expected.

**Environment**
I tested two environments, both have the described behavior:
- TYPO3 version(s): 11.5.38 / 12.4.20
- cart version: 8.2.0 / 9.0.1
- cart_products version: 4.2.1 / 5.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): 11.5.38: no / 12.4.20: yes
- OS: Windows 11 / Windows 10

**Additional Explanation**
This is **not** working:
![Screenshot 2024-10-09 110717](https://github.com/user-attachments/assets/dbdd0662-827e-436e-83ef-39bdd83be19b)

This is working:
![Screenshot 2024-10-09 110654](https://github.com/user-attachments/assets/b420eaa3-d581-43db-9e90-85cbc4ea5e52)

The code snippet in the site configuration:
```yaml
routeEnhancers:
  tx_cartordersglab_products:
      type: Extbase
      extension: CartOrdersGlab
      plugin: Products
      routes:
        - routePath: '/{product_title}'
          _controller: 'Product::show'
          _arguments:
            product_title: product
      defaultController: 'Product::show'
      aspects:
        product_title:
          type: PersistedAliasMapper
          tableName: tx_cartordersglab_domain_model_product_product
          routeFieldName: path_segment
```

**Possible Causes**
- Could something be missing in the cartproducts:link.product viewhelper used to create the links?
- Could the route enhancer configuration miss something?
